Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bloggy.urls")),
    # The url below will handle our auth page using django, these two urls are necessary in this order
    #Reference of LOGIN_REDIRECT_URL & LOGOUT_REDIRECT_URL in the settings.py is necessary to make 'login' and 'logout' easier just using those words in the links
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
]

Blog/bloggy/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # path('', views.home, name="home"),
    path('', views.HomeView.as_view(), name='home'),
    path('article/<int:pk>', views.ArticleDetailsView.as_view(), name='article-details'),
    path('article/edit/<int:pk>', views.UpdateArticleView.as_view(), name='update-post'),
    path('article/remove/<int:pk>', views.DeleteArticleView.as_view(), name='delete-post'),
    path('article/add-post/', views.AddPostView.as_view(), name='add-post'),
    path('article/add-category', views.AddCategorytView.as_view(), name='add-category'),
    path('article/category/<str:category>/', views.FilterArticleCategorytView, name='blog-category'),
    path('article/category/edit/<int:pk>/', views.UpdateCategoryView.as_view(), name='update-category'),
    path('article/category/remove/<int:pk>/', views.DeleteCategoryView.as_view(), name='delete-category'),
    path('article/category/remove/<int:pk>/', views.DeleteCategoryView.as_view(), name='delete-category'),
    path('article/category-list', views.CategoryListView, name='category-list'),
    path('article/like/<int:pk>', views.LikedPostView, name='post-like'),
    path('article/<int:pk>/comment/', views.AddCommentPostView.as_view(), name='post-comment'),
]

Blog/members/urls.py
from django.urls import path
from .views import UserRegisterView

app_name = 'members'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
]

Blog/bloggy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=230)
    
    def __str__(self):
        return f'{self.name}'
    def get_absolute_url(self):
        return reverse('blog:home')

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField()
    post_date = models.DateField(auto_now_add=True)
    snippet = models.TextField(max_length=230)
    category = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='post_likes')
    
    def total_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return f'{self.title} | {self.author}'
    
    # This method allows for us to have a url to which the page can go to after the form submission to avoid the error below
    # "No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model."
    def get_absolute_url(self):
        return reverse('blog:article-details', args=[str(self.id)]) # The arg refers to the article that was just created's Id as the page to load to. A url without arguments wouldn't need it
        # return reverse('blog: home') # The arg refers to the article that was just created's Id as the page to load to. A url without arguments wouldn't need it
        
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField(verbose_name='Comment...')
    post_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.post.title} by {self.author.username}'
    
    def get_absolute_url(self):
        return reverse('blog:article-details', args=[str(self.post.pk)]) 

Blog/bloggy/forms.py
from django import forms
from .models import Post, Category, Comment

category_options = Category.objects.all().values_list('name', 'name') # This returns an object with a list a queryset

# Turning the 'category_options' queryset into a python list to use for choices
category_options_list = []
for item in category_options:
    category_options_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'snippet','category', 'body')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control col-md-4'},),
            'snippet': forms.Textarea(attrs={'class': 'form-control col-md-4', 'rows':4},),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control col-md-4', 'value':'', 'id':'author', 'type':'hidden'}),
            'category': forms.Select(attrs={'class': 'form-control col-md-4'}, choices = category_options), # The 'choices'  has be the first in line
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'description')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'},),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows':4},),
        }

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'snippet','category','body')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'},),
            'snippet': forms.Textarea(attrs={'class': 'form-control', 'rows':4},),
            'category': forms.Select(choices = category_options, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'post', 'body')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'post': forms.TextInput(attrs={'class': 'form-control', 'value':'{{post.id}}', 'id':'post', 'type':'hidden'},),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value':'{{user.id}}', 'id':'author', 'type':'hidden'}),
            'body': forms.TextInput(attrs={'id':'comments', 'placeholder':'Enter comment...'}),
        }

Blog/bloggy/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import PostForm, UpdateForm, CategoryForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from .forms import CommentForm

# Create your views here.
# def home(request):
#     context = {
#         'page_name': 'Home Page',
#     }
#     return render(request, 'home.html', context)

class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-post_date']
    paginate_by = 5
    
    # This method that will allow for a context dict to be added onto the view
    def get_context_data(self, *args,**kwargs):
        category_list = Category.objects.all()
        recent_post = Post.objects.all().order_by('-post_date')[:4]
        context = super(HomeView, self).get_context_data(*args, **kwargs) # The view inside is the view the method is used in
        context['category_list'] = category_list
        context['recent_post'] = recent_post
        return context

def LikedPostView(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    liked = False
    
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    
    return HttpResponseRedirect(reverse('blog:article-details', args=[str(pk)]))

class AddCommentPostView(CreateView):
    model = Comment
    form_class = CommentForm

class ArticleDetailsView(DetailView):
    model = Post
    template_name = 'article_details.html'
    
    # This method that will allow for a context dict to be added onto the view
    def get_context_data(self, *args,**kwargs):
        category_list = Category.objects.all()
        context = super(ArticleDetailsView, self).get_context_data(*args, **kwargs) # The view inside is the view the method is used in
        current_post = get_object_or_404(Post, id=self.kwargs['pk']) # Fetches the post for the current post's id
        total_likes = current_post.total_likes()
        
        liked = False
        if current_post.likes.filter(id=self.request.user.id).exists():
            liked = True
        
        # adding context elements
        context['category_list'] = category_list
        context['total_likes'] = total_likes
        context['liked'] = liked
        context['comment_form'] = CommentForm
        return context
    
class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    
class AddCategorytView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'add_category.html'

def FilterArticleCategorytView(request, category):
    items = Post.objects.filter(category=category).order_by('-post_date')
    cats = Category.objects.filter(name=category)
    recent_post = items.order_by('-post_date')[:4]
    category_list = Category.objects.all()
    paginator = Paginator(items, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'category': category,
        'posts': items,
        'cats': cats,
        'category_list': category_list,
        'page_obj': page_obj,
        'paginator': paginator,
        'recent_post': recent_post,
    }
    return render(request, 'filter_article_category.html', context)

def CategoryListView(request):
    category_list = Category.objects.all()
    category_list = category_list.order_by('name')
    context = {
        'category_menu_list': category_list,
    }
    return render(request, 'categories.html', context)

class UpdateArticleView(UpdateView):
    model = Post
    form_class = UpdateForm
    template_name = 'update_post.html'

class DeleteArticleView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('blog:home') # This is added to redirect to the chosen page with the DeleteView avoid the following error: "No URL to redirect to. Provide a success_url."

class UpdateCategoryView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'update_category.html'

class DeleteCategoryView(DeleteView):
    model = Category
    template_name = 'delete_category.html'
    success_url = reverse_lazy('blog:home') # This is added to redirect to the chosen page with the DeleteView avoid the following error: "No URL to redirect to. Provide a success_url."

Blog/bloggy/templates/partials/_footer.html
<footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="container d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-body-secondary">&copy; 2025 Company, Inc</p>
    
        <a href="/" class="col-md-3 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        </a>
    
        <ul class="nav col-md-5 justify-content-end">
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
        </ul>
    </div>
</footer>

Blog/bloggy/templates/partials/_header.html
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        VG Logo
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" data-bs-theme="dark">
        <li><a href="#" class="nav-link px-2 text-white">Home</a></li>
        <li><a href="{% url 'blog:home' %}" class="nav-link px-2 text-white">Blogs</a></li>
        <li><a href="http://127.0.0.1:8001/tutorials/" class="nav-link px-2 text-white">Tutorials</a></li>
        <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" aria-labelledby="dropdownMenuButtonDark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Tutorials
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="http://127.0.0.1:8001/tutorials/">Written Tutorials</a></li>
                <li><a class="dropdown-item disabled" href="#">Video Tutorials</a></li>
            </ul>
          </li> -->
        <li><a href="#" class="nav-link px-2 text-white">Practice</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Store</a></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
        <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
      </form>

      <!-- Dark mode -->
      {% if user.is_authenticated %}
      <div class="dropdown text-end" data-bs-theme="dark">
        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownMenuButtonDark">
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li>
            <!-- The format to allow logout to work well. -->
            <a class="dropdown-item">
              <form action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="nav-link" value="Sign out"></input>
              </form>
            </a>
        </li>
        </ul>
      </div>
      {% else %}
      <div class="text-end">
        <a href="{% url 'login' %}">
            <button type="button" class="btn btn-outline-light me-2">Login</button></a>
        <a href="{% url 'members:register' %}">
            <button type="button" class="btn btn-warning">Register</button>
        </a>
      </div>
      {% endif %}
    </div>
  </div>
    </div>
  </div>
</header>

<div class="b-example-divider"></div>

<!-- Light mode -->
<!-- <header class="p-3 mb-3 border-bottom" data-bs-theme="light">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start" aria-labelledby="dropdownMenuButtonLight">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
        VS Logo
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Overview</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Inventory</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Customers</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Products</a></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
        <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
      </form>

       {% if user.is_authenticated %}
      <div class="dropdown text-end">
        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <ul class="dropdown-menu text-small">
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li>
            
            <a class="dropdown-item">
              <form action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="nav-link" value="Sign out"></input>
              </form>
            </a>
        </li>
        </ul>
      </div>
      {% else %}
      <div class="text-end">
        <a href="{% url 'login' %}">
            <button type="button" class="btn btn-outline-success me-2">Login
            </button></a>
        <a href="{% url 'members:register' %}">
            <button type="button" class="btn btn-outline-primary">Register
            </button>
        </a>
      </div>
      {% endif %}
    </div>
  </div>
</header> -->

<div class="bg-body-secondary position-sticky" style="top: 0;">
    <header class="d-flex justify-content-center py-3">
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'blog:home' %}" class="nav-link px-2 text-secondary">Blogs</a></li>
        <li><a href="{% url 'blog:add-post' %}" class="nav-link px-2 text-secondary">Add post</a></li>
        <li><a href="{% url 'blog:add-category' %}" class="nav-link px-2 text-secondary">Add category</a></li>
        {% if category_list%}
          <!-- The category list -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-secondary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              {% for category in category_list %}
                <li><a class="dropdown-item text-secondary" href="{% url 'blog:blog-category' category.name %}">{{category}}</a></li>
              {% endfor %}
            </ul>
          </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link text-secondary" href="{% url 'blog:category-list' %}">Categories</a>
        </li>
        {% endif %}
      </ul>
    </header>
  </div>