Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bloggy.urls")),
    # The url below will handle our auth page using django, these two urls are necessary in this order
    #Reference of LOGIN_REDIRECT_URL & LOGOUT_REDIRECT_URL in the settings.py is necessary to make 'login' and 'logout' easier just using those words in the links
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
]

Blog/bloggy/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # path('', views.home, name="home"),
    path('', views.HomeView.as_view(), name='home'),
    path('article/<int:pk>', views.ArticleDetailsView.as_view(), name='article-details'),
    path('article/edit/<int:pk>', views.UpdateArticleView.as_view(), name='update-post'),
    path('article/remove/<int:pk>', views.DeleteArticleView.as_view(), name='delete-post'),
    path('article/add-post/', views.AddPostView.as_view(), name='add-post'),
    path('article/add-category', views.AddCategorytView.as_view(), name='add-category'),
    path('article/category/<str:category>/', views.FilterArticleCategorytView, name='blog-category'),
    path('article/category/edit/<int:pk>/', views.UpdateCategoryView.as_view(), name='update-category'),
    path('article/category/remove/<int:pk>/', views.DeleteCategoryView.as_view(), name='delete-category'),
    path('article/category/remove/<int:pk>/', views.DeleteCategoryView.as_view(), name='delete-category'),
    path('article/category-list', views.CategoryListView, name='category-list'),
    path('article/like/<int:pk>', views.LikedPostView, name='post-like'),
    path('article/<int:pk>/comment/', views.AddCommentPostView.as_view(), name='post-comment'),
]

Blog/bloggy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=230)
    
    def __str__(self):
        return f'{self.name}'
    def get_absolute_url(self):
        return reverse('blog:home')

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField()
    post_date = models.DateField(auto_now_add=True)
    snippet = models.TextField(max_length=230)
    category = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='post_likes')
    
    def total_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return f'{self.title} | {self.author}'
    
    # This method allows for us to have a url to which the page can go to after the form submission to avoid the error below
    # "No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model."
    def get_absolute_url(self):
        return reverse('blog:article-details', args=[str(self.id)]) # The arg refers to the article that was just created's Id as the page to load to. A url without arguments wouldn't need it
        # return reverse('blog: home') # The arg refers to the article that was just created's Id as the page to load to. A url without arguments wouldn't need it
        
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField(verbose_name='Comment...')
    post_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.post.title} by {self.author.username}'
    
    def get_absolute_url(self):
        return reverse('blog:article-details', args=[str(self.post.pk)]) 

Blog/bloggy/forms.py
from django import forms
from .models import Post, Category, Comment

category_options = Category.objects.all().values_list('name', 'name') # This returns an object with a list a queryset

# Turning the 'category_options' queryset into a python list to use for choices
category_options_list = []
for item in category_options:
    category_options_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'snippet','category', 'body')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control col-md-4'},),
            'snippet': forms.Textarea(attrs={'class': 'form-control col-md-4', 'rows':4},),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control col-md-4', 'value':'', 'id':'author', 'type':'hidden'}),
            'category': forms.Select(attrs={'class': 'form-control col-md-4'}, choices = category_options), # The 'choices'  has be the first in line
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'description')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'},),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows':4},),
        }

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'snippet','category','body')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'},),
            'snippet': forms.Textarea(attrs={'class': 'form-control', 'rows':4},),
            'category': forms.Select(choices = category_options, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'post', 'body')
        
        #Styling the fields of the form with bootsrap
        widgets = {
            'post': forms.TextInput(attrs={'class': 'form-control', 'value':'{{post.id}}', 'id':'post', 'type':'hidden'},),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value':'{{user.id}}', 'id':'author', 'type':'hidden'}),
            'body': forms.TextInput(attrs={'id':'comments', 'placeholder':'Enter comment...'}),
        }

Blog/bloggy/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import PostForm, UpdateForm, CategoryForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from .forms import CommentForm

# Create your views here.
# def home(request):
#     context = {
#         'page_name': 'Home Page',
#     }
#     return render(request, 'home.html', context)

class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-post_date']
    paginate_by = 5
    
    # This method that will allow for a context dict to be added onto the view
    def get_context_data(self, *args,**kwargs):
        category_list = Category.objects.all()
        recent_post = Post.objects.all().order_by('-post_date')[:4]
        context = super(HomeView, self).get_context_data(*args, **kwargs) # The view inside is the view the method is used in
        context['category_list'] = category_list
        context['recent_post'] = recent_post
        return context

def LikedPostView(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    liked = False
    
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    
    return HttpResponseRedirect(reverse('blog:article-details', args=[str(pk)]))

class AddCommentPostView(CreateView):
    model = Comment
    form_class = CommentForm

class ArticleDetailsView(DetailView):
    model = Post
    template_name = 'article_details.html'
    
    # This method that will allow for a context dict to be added onto the view
    def get_context_data(self, *args,**kwargs):
        category_list = Category.objects.all()
        context = super(ArticleDetailsView, self).get_context_data(*args, **kwargs) # The view inside is the view the method is used in
        current_post = get_object_or_404(Post, id=self.kwargs['pk']) # Fetches the post for the current post's id
        total_likes = current_post.total_likes()
        
        liked = False
        if current_post.likes.filter(id=self.request.user.id).exists():
            liked = True
        
        # adding context elements
        context['category_list'] = category_list
        context['total_likes'] = total_likes
        context['liked'] = liked
        context['comment_form'] = CommentForm
        return context
    
class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    
class AddCategorytView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'add_category.html'

def FilterArticleCategorytView(request, category):
    items = Post.objects.filter(category=category).order_by('-post_date')
    cats = Category.objects.filter(name=category)
    recent_post = items.order_by('-post_date')[:4]
    category_list = Category.objects.all()
    paginator = Paginator(items, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'category': category,
        'posts': items,
        'cats': cats,
        'category_list': category_list,
        'page_obj': page_obj,
        'paginator': paginator,
        'recent_post': recent_post,
    }
    return render(request, 'filter_article_category.html', context)

def CategoryListView(request):
    category_list = Category.objects.all()
    category_list = category_list.order_by('name')
    context = {
        'category_menu_list': category_list,
    }
    return render(request, 'categories.html', context)

class UpdateArticleView(UpdateView):
    model = Post
    form_class = UpdateForm
    template_name = 'update_post.html'

class DeleteArticleView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('blog:home') # This is added to redirect to the chosen page with the DeleteView avoid the following error: "No URL to redirect to. Provide a success_url."

class UpdateCategoryView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'update_category.html'

class DeleteCategoryView(DeleteView):
    model = Category
    template_name = 'delete_category.html'
    success_url = reverse_lazy('blog:home') # This is added to redirect to the chosen page with the DeleteView avoid the following error: "No URL to redirect to. Provide a success_url."

Blog/bloggy/templates/add_category.html
{% extends 'base.html' %}
{% load static %}

<!-- Making such that the title changes on the tab in ref to the base page -->
{% block title%}
Create A New Blog Category
{% endblock %}

{% block content %}
    <h1>Add Category</h1><br>
    {% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-secondary">Add Category</button>
        <button class="btn btn-danger"><a href="{% url 'blog:home' %}" style="text-decoration: none; color: white;">Cancel</a></button>
    </form>
    {% else %}
    <p>You are not allowed here. Login to access this page.</p>
    {% endif %}

{% endblock %}

Blog/bloggy/templates/add_post.html
{% extends 'base.html' %}
{% load static %}

<!-- Making such that the title changes on the tab in ref to the base page -->
{% block title%}
Create A New Blog Post
{% endblock %}

{% block content %}
    <h1>Add Post</h1><br>
    {% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p | safe}}
        <button class="btn btn-secondary">Post</button>
        <button class="btn btn-danger"><a href="{% url 'blog:home' %}" style="text-decoration: none; color: white;">Cancel Post</a></button>
    </form>
    {% else %}
    <p>You are not allowed here. Login to access this page.</p>
    {% endif %}
<script>
    // Fetching current user id and placing it on the form
    let user_id = "{{user.id}}";
    author_input = document.getElementById('author').value = user_id;
</script>
{% endblock %}

Blog/bloggy/templates/article_details.html
{% extends 'base.html' %}
{% load static %}

<!-- Making such that the title changes on the tab in ref to the base page -->
{% block title%}
{{post.title}}
{% endblock %}

{% block content %}
<main class="container">
    <br>
  <!-- Current post -->
    <div class="row g-5">
      <div class="col-md-8">
        <article class="blog-post">
          <h2 class="display-5 link-body-emphasis mb-1">
            <a href="{% url 'blog:article-details' post.pk %}" style="text-decoration: none; color: black;">
            {{post.title}}
            </a>
          </h2>
          <small>
            {% if user.is_authenticated %}
                {% if user.id == post.author.id%}
                    - <small><a href="{% url 'blog:update-post' post.pk%}">Edit</a> <a href="{% url 'blog:delete-post' post.pk%}">Delete</a></small>
                {% endif %}
            {% endif %}
          </small>
          <p class="blog-post-meta">{{post.post_date}}  <small> - 
            <a href="{% url 'blog:blog-category' post.category %}">{{post.category}}</a> by
            {% if post.author.first_name %}
                {{post.author.first_name}} {{post.author.last_name}}
            {% else %}
                {{post.author}}
            {% endif %}
        </small>
  
          <p>{{post.body | safe }}</p>
        </article>
  
      </div>
      
      <!-- Start of the side-bar -->
       
      <!-- Short description to tell your visitors a little bit about your publication, writers, content, or something else entirely -->
      <div class="col-md-4">
        <div class="position-sticky" style="top: 2rem;">
          <div class="p-4 mb-3 bg-body-tertiary rounded">
            <h4 class="fst-italic">About</h4>
            <p class="mb-0">{{ post.snippet}}</p>
          </div>
        
          <!-- Other platform to have access -->
          <div class="p-4">
            <h4 class="fst-italic">Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <p>
        <a href="{% url 'blog:home' %}" class="btn btn-secondary">Back</a>
    </p>
  <!-- Comment secction edit -->
    <hr>
  <form action="{% url 'blog:post-like' post.pk %}" method="POST">
    {% csrf_token %}
    {% if user.is_authenticated %}
        {% if liked %}
        <button name="post_id" value="{{ post.pk }}" class="btn btn-primary position-relative">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a10 10 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733q.086.18.138.363c.077.27.113.567.113.856s-.036.586-.113.856c-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.2 3.2 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.8 4.8 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
              </svg> Liked
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                {{total_likes}}
              <span class="visually-hidden">{{total_likes}} unlike</span>
            </span>
        </button>
        {% else%}
            {% if liked != 0 %}
                <button name="post_id" value="{{ post.pk }}" class="btn btn-primary position-relative">Like</button>
            {% else %}
                <button name="post_id" value="{{ post.pk }}" class="btn btn-primary position-relative">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                        <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2 2 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a10 10 0 0 0-.443.05 9.4 9.4 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a9 9 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.2 2.2 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.9.9 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                    </svg> Like
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                        {{total_likes}}
                    <span class="visually-hidden">{{total_likes}} like</span>
                    </span>
                </button>
            {% endif %}
        {% endif%}
    {% else %}
        <a href="{% url 'login' %}">Login</a> to be able to like - {{total_likes}} Likes
    {% endif%}
    </form>
    <!-- End comment section edit -->
<br>
<h2>Comments:</h2>

{% if user.is_authenticated %}
    <form class="col-md-8" action="{% url 'blog:post-comment' post.pk %}" method="POST">
        {% csrf_token %}
        {{comment_form }}
        <button type="submit" class="btn btn-primary">Comment</button>
    </form>
{% endif %}

<br><br>
{% if not post.comments.all %}
<h2>Comments:</h2>
    No comments yet...
{% else %}
<h2>{{post.comments.all|length}} Comments:</h2>
    {% for comment in post.comments.all %}
        <strong>
            {{ comment.author}}
            {{ comment.post_date}}
        </strong>
        <p>
            {{ comment.body }}
        </p>
    {% endfor %}
{% endif %}
<script>
    // Fetching current user id and placing it on the form
    let user_id = "{{user.id}}";
    author_input = document.getElementById('author').value = user_id;
    let post_id = "{{post.pk}}";
    post_input = document.getElementById('post').value = post_id;
</script>
  </main>
{% endblock %}

Blog/bloggy/templates/categories.html
{% extends 'base.html' %}
{% load static %}

<!-- Making such that the title changes on the tab in ref to the base page -->
{% block title%}
Blog Categories - VG Blog
{% endblock %}

{% block content %}
<h1>
    Categories
</h1>
    {% for category in category_menu_list %}
      <!-- <h3><a class="dropdown-item" href="{% url 'blog:blog-category' category %}">{{category}}</a></h3> -->
      <div class="list-group">
        <button type="button" class="list-group-item list-group-item-action">
          <a class="dropdown-item" href="{% url 'blog:blog-category' category %}">{{category}}

      <!-- Filters this information only for people in the manager group. -->
      {% for group in user.groups.all%}
        {% if "Blog manager" or "Manager" in group.name %}
          <small>- <a href="{% url 'blog:update-category' category.pk %}">Edit</a> <a href="{% url 'blog:delete-category' category.pk %}">Delete</a></small>
        {% endif %}
      {% endfor %}
          </a>
        </button>
      </div>
    {% endfor %}
{% endblock %}

Blog/bloggy/templates/delete_category.html
{% extends 'base.html' %}
{% load static %}

<!-- Making such that the title changes on the tab in ref to the base page -->
{% block title%}
Delete - {{post.category}}
{% endblock %}

{% block content %}
    <h1>Delete Category: {{post.category}}</h1><br>

    {% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        <strong>Are you sure you want to delete this category?</strong> <br><br>
        <p>
            <button class="btn btn-secondary">Delete</button>
            <button class="btn btn-danger"><a href="{% url 'blog:home' %}" style="text-decoration: none; color: white;">Cancel</a></button>
        </p>
    </form>

    {% else %}
    <p>You are not allowed here. Login to access this page.</p>
    {% endif %}

{% endblock %}

Blog/bloggy/templates/filter_article_category.html
{% extends 'base.html' %}
{% load static %}

<!-- Making such that the title changes on the tab in ref to the base page -->
{% block title%}
{{post.title}}
{% endblock %}

{% block content %}
    <h1>
        {{category | title}}
    </h1>
    <main class="container">
        <br>
    <!-- Current post -->
    {% if posts %}
        <div class="row g-5">
        <div class="col-md-8">
            {% for post in page_obj %}
            <article class="blog-post">
            <h2 class="display-5 link-body-emphasis mb-1">
                <a href="{% url 'blog:article-details' post.pk %}" style="text-decoration: none; color: black;">
                {{post.title}}
                </a>
            </h2>
            <small>
                {% if user.is_authenticated %}
                    {% if user.id == post.author.id %}
                        - <small><a href="{% url 'blog:update-post' post.pk%}">Edit</a> <a href="{% url 'blog:delete-post' post.pk%}">Delete</a></small>
                    {% endif %}
                {% endif %}
            </small>
            <p class="blog-post-meta">{{post.post_date}} <small> - 
                <a href="{% url 'blog:blog-category' post.category %}">{{post.category}}</a> by
                {% if post.author.first_name %}
                    {{post.author.first_name}} {{post.author.last_name}}
                {% else %}
                    {{post.author}}
                {% endif %}
            </small>
    
            <p>{{post.snippet}}</p>
            <hr>
            {% endfor %}
            </article>
    
            <!-- Pagination section -->
            {% if page_obj.paginator.num_pages == 1%}
            {% else%}
            <div class="pagination">
                <nav aria-label="...">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                      <li class="page-item">
                        <a class="page-link" href="?page=1">&Lang;</a>
                      </li>
                      <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lang;</a>
                      </li>
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                      {% endif %}
                      <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ page_obj.number }}</a>
                      </li>
                      {% if page_obj.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                      <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rang;</a>
                      </li>
                      <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&Rang;</a>
                      </li>
                      {% endif %}
                    </ul>
                  </nav>
            </div>
            {% endif %}
        </div>
        
        <!-- Start of the side-bar -->
        
        <!-- Short description to tell your visitors a little bit about your publication, writers, content, or something else entirely -->
        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
            <div class="p-4 mb-3 bg-body-tertiary rounded">
                <h4 class="fst-italic">About</h4>
                {% for cat in cats %}
                <p class="mb-0">{{cat.description}}</p>
                {% endfor%}
            </div>

            <!-- Section for recent posts -->

            <div>
                <h4 class="fst-italic">Related Recent posts</h4>
                <ul class="list-unstyled">
                    {% for post in recent_post %}
                <li>
                    <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                    <svg class="bd-placeholder-img" width="100%" height="96" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
                    <div class="col-lg-8">
                        <h6 class="mb-0">{{post.title}}</h6>
                        <small class="text-body-secondary">{{post.post_date}}</small>
                    </div>
                    </a>
                </li>
                {% endfor %}
                </ul>
            </div>
            
            <!-- Filtering the blog post per month in year. e.g: March 2024 -->
            <div class="p-4">
                <h4 class="fst-italic">Archives</h4>
                <ol class="list-unstyled mb-0">
                <li><a href="#">March 2021</a></li>
                <li><a href="#">February 2021</a></li>
                <li><a href="#">January 2021</a></li>
                <li><a href="#">December 2020</a></li>
                <li><a href="#">November 2020</a></li>
                <li><a href="#">October 2020</a></li>
                <li><a href="#">September 2020</a></li>
                <li><a href="#">August 2020</a></li>
                <li><a href="#">July 2020</a></li>
                <li><a href="#">June 2020</a></li>
                <li><a href="#">May 2020</a></li>
                <li><a href="#">April 2020</a></li>
                </ol>
            </div>
            
            <!-- Other platform to have access -->
            <div class="p-4">
                <h4 class="fst-italic">Elsewhere</h4>
                <ol class="list-unstyled">
                <li><a href="#">GitHub</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                </ol>
            </div>
            </div>
        </div>
        </div>
    </main>
    {% else %}
        <h2>{{category}} is not a valid category.</h2>
    {% endif %}
{% endblock %}

Blog/bloggy/templates/update_category.html
{% extends 'base.html' %}
{% load static %}

<!-- Making such that the title changes on the tab in ref to the base page -->
{% block title%}
Edit - {{post.category}}
{% endblock %}

{% block content %}
    <h1>Update Category</h1><br>

    {% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-secondary">Update</button>
        <button class="btn btn-danger"><a href="{% url 'blog:blog-category' category.name %}" style="text-decoration: none; color: white;">Cancel Update</a></button>
    </form>
    {% else %}
    <p>You are not allowed here. Login to access this page.</p>
    {% endif %}
    
{% endblock %}